# Generated by Django 4.2.2 on 2023-06-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='keywords',
            new_name='Keywords',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='location',
            new_name='Location',
        ),
        migrations.AddField(
            model_name='form',
            name='Number',
            field=models.CharField(default=1, max_length=30, verbose_name='Number'),
            preserve_default=False,
        ),
    ]
