# Generated by Django 4.2.2 on 2023-07-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_keywords_form_keywords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Keywords',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='Location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='form',
            name='Number',
        ),
        migrations.AddField(
            model_name='form',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Number'),
            preserve_default=False,
        ),
    ]
